# Generated by Django 6.0.5 on 2026-05-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='food_type',
            field=models.BooleanField(default=False),
        ),
    ]
