# Generated by Django 4.2.30 on 2026-07-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.ImageField(null=True, upload_to='files/'),
        ),
    ]
