# Generated by Django 4.2.30 on 2026-08-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Manager'), (2, 'Employee'), (3, 'User')], default=0),
        ),
    ]
